#!/usr/bin/env python3
"""Generate the initial original item bank for the SAT Math readiness prototype."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data" / "synthetic" / "item_bank.json"


ORIGINALITY_NOTE = (
    "Original item written for this public-safe diagnostic prototype; not copied "
    "or closely paraphrased from SAT, ACT, AP, state exam, commercial publisher, "
    "or school-private materials."
)


def mcq(
    item_id: str,
    module: int,
    position: int,
    domain: str,
    subdomain: str,
    skill_statement: str,
    difficulty_band: str,
    stem_html: str,
    choices: list[tuple[str, str]],
    correct_answer: str,
    feedback: dict[str, str],
    general_feedback: str,
    misconception_tags: list[str],
    remediation_tag: str,
    mastery_check_target: str,
) -> dict:
    return {
        "item_id": item_id,
        "module": module,
        "position": position,
        "domain": domain,
        "subdomain": subdomain,
        "skill_statement": skill_statement,
        "difficulty_band": difficulty_band,
        "item_type": "multiple_choice",
        "stem_html": stem_html,
        "choices": [
            {"choice_id": choice_id, "html": html, "is_correct": choice_id == correct_answer}
            for choice_id, html in choices
        ],
        "correct_answer": correct_answer,
        "accepted_answer_rules": [],
        "distractor_feedback": feedback,
        "general_feedback": general_feedback,
        "misconception_tags": misconception_tags,
        "remediation_tag": remediation_tag,
        "mastery_check_target": mastery_check_target,
        "review_status": "draft",
        "source_originality_note": ORIGINALITY_NOTE,
    }


def numeric(
    item_id: str,
    module: int,
    position: int,
    domain: str,
    subdomain: str,
    skill_statement: str,
    difficulty_band: str,
    stem_html: str,
    correct_answer: str,
    accepted_answer_rules: list[dict],
    general_feedback: str,
    misconception_tags: list[str],
    remediation_tag: str,
    mastery_check_target: str,
) -> dict:
    return {
        "item_id": item_id,
        "module": module,
        "position": position,
        "domain": domain,
        "subdomain": subdomain,
        "skill_statement": skill_statement,
        "difficulty_band": difficulty_band,
        "item_type": "numeric_student_produced_response",
        "stem_html": stem_html,
        "choices": [],
        "correct_answer": correct_answer,
        "accepted_answer_rules": accepted_answer_rules,
        "distractor_feedback": {},
        "general_feedback": general_feedback,
        "misconception_tags": misconception_tags,
        "remediation_tag": remediation_tag,
        "mastery_check_target": mastery_check_target,
        "review_status": "draft",
        "source_originality_note": ORIGINALITY_NOTE,
    }


ITEMS = [
    mcq(
        "ITEM-001",
        1,
        1,
        "Algebra",
        "Linear equations in one variable",
        "Solve a one-variable linear equation.",
        "easy",
        "<p>If 3x + 5 = 20, what is the value of x?</p>",
        [("A", "5"), ("B", "15"), ("C", "25/3"), ("D", "-5")],
        "A",
        {
            "B": "This subtracts 5 but does not divide by 3.",
            "C": "This adds 5 instead of subtracting 5 before dividing.",
            "D": "This uses the opposite sign after solving.",
        },
        "Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5.",
        ["inverse-operation error", "sign error"],
        "linear-equation-solving",
        "Solve a one-variable equation with one distribution or inverse-operation step.",
    ),
    mcq(
        "ITEM-002",
        1,
        2,
        "Algebra",
        "Linear equations in two variables",
        "Rewrite a linear equation to identify slope.",
        "easy",
        "<p>The equation 2y - 4x = 10 represents a line. What is the slope of the line?</p>",
        [("A", "2"), ("B", "-2"), ("C", "4"), ("D", "5")],
        "A",
        {
            "B": "This keeps the sign from -4x instead of solving for y.",
            "C": "This uses the coefficient of x before dividing by 2.",
            "D": "This identifies the y-intercept, not the slope.",
        },
        "Rewrite as 2y = 4x + 10, then y = 2x + 5. The slope is 2.",
        ["slope-intercept confusion", "coefficient scaling error"],
        "linear-equation-slope",
        "Rewrite a two-variable linear equation in slope-intercept form.",
    ),
    mcq(
        "ITEM-003",
        1,
        3,
        "Problem-Solving and Data Analysis",
        "Ratios, rates, proportional relationships, and units",
        "Compute and interpret a unit rate.",
        "easy",
        "<p>A train travels 144 miles in 3 hours at a constant speed. What is the speed, in miles per hour?</p>",
        [("A", "36"), ("B", "48"), ("C", "141"), ("D", "432")],
        "B",
        {
            "A": "This divides by 4 rather than by the 3 hours given.",
            "C": "This subtracts the time from the distance.",
            "D": "This multiplies distance by time instead of dividing.",
        },
        "Divide miles by hours: 144 / 3 = 48 miles per hour.",
        ["unit-rate error"],
        "unit-rate-reasoning",
        "Find a unit rate from a proportional context.",
    ),
    mcq(
        "ITEM-004",
        1,
        4,
        "Geometry and Trigonometry",
        "Area and volume formulas",
        "Use a triangle area formula.",
        "easy",
        "<p>A triangle has base 14 units and height 9 units. What is its area, in square units?</p>",
        [("A", "23"), ("B", "63"), ("C", "126"), ("D", "196")],
        "B",
        {
            "A": "This adds the base and height instead of using area.",
            "C": "This multiplies base by height but omits the factor of 1/2.",
            "D": "This squares the base instead of using both dimensions.",
        },
        "Triangle area is (1/2)bh = (1/2)(14)(9) = 63.",
        ["formula selection error"],
        "triangle-area",
        "Apply the triangle area formula from given base and height.",
    ),
    mcq(
        "ITEM-005",
        1,
        5,
        "Algebra",
        "Linear inequalities in one or two variables",
        "Solve a linear inequality with a negative coefficient.",
        "easy",
        "<p>Which inequality is equivalent to 5 - 2x &gt; 13?</p>",
        [("A", "x &gt; -4"), ("B", "x &lt; -4"), ("C", "x &gt; 4"), ("D", "x &lt; 4")],
        "B",
        {
            "A": "This does not reverse the inequality when dividing by -2.",
            "C": "This misses both the negative value and the inequality reversal.",
            "D": "This reverses the inequality but loses the negative value.",
        },
        "Subtract 5 to get -2x > 8. Dividing by -2 reverses the inequality, so x < -4.",
        ["inequality reversal error", "sign error"],
        "linear-inequality-solving",
        "Solve an inequality that requires reversing the inequality sign.",
    ),
    mcq(
        "ITEM-006",
        1,
        6,
        "Advanced Math",
        "Equivalent expressions",
        "Simplify a rational expression by factoring.",
        "easy",
        "<p>For x not equal to 3, which expression is equivalent to (x^2 - 9)/(x - 3)?</p>",
        [("A", "x - 3"), ("B", "x + 3"), ("C", "x^2 + 3"), ("D", "1/(x + 3)")],
        "B",
        {
            "A": "This cancels the wrong factor after factoring the numerator.",
            "C": "This does not factor the difference of squares.",
            "D": "This reverses the simplified expression.",
        },
        "Factor x^2 - 9 as (x - 3)(x + 3). Cancel x - 3 to get x + 3.",
        ["factoring error", "rational-expression error"],
        "equivalent-expressions",
        "Factor and simplify a rational expression with a removable factor.",
    ),
    mcq(
        "ITEM-007",
        1,
        7,
        "Algebra",
        "Systems of two linear equations in two variables",
        "Solve a 2-by-2 linear system.",
        "medium",
        "<p>If x + y = 11 and x - y = 3, what is the value of x?</p>",
        [("A", "4"), ("B", "7"), ("C", "8"), ("D", "14")],
        "B",
        {
            "A": "This is the value of y, not x.",
            "C": "This comes from subtracting equations incorrectly.",
            "D": "This adds the equations but does not divide by 2.",
        },
        "Add the equations to get 2x = 14, so x = 7.",
        ["system-elimination error"],
        "systems-linear",
        "Use elimination to solve a two-equation linear system.",
    ),
    mcq(
        "ITEM-008",
        1,
        8,
        "Advanced Math",
        "Nonlinear functions",
        "Evaluate a quadratic function.",
        "medium",
        "<p>If f(x) = x^2 - 4x, what is f(6)?</p>",
        [("A", "4"), ("B", "12"), ("C", "20"), ("D", "36")],
        "B",
        {
            "A": "This computes (6 - 4)^2 instead of substituting 6 into both terms of x^2 - 4x.",
            "C": "This uses 6^2 - 4 instead of 6^2 - 4(6).",
            "D": "This evaluates only 6^2.",
        },
        "Substitute x = 6: f(6) = 6^2 - 4(6) = 36 - 24 = 12.",
        ["function-substitution error", "order-of-operations error"],
        "function-evaluation",
        "Evaluate a nonlinear function at a given input.",
    ),
    mcq(
        "ITEM-009",
        1,
        9,
        "Problem-Solving and Data Analysis",
        "Percentages",
        "Apply a percent increase.",
        "medium",
        "<p>A price of $80 is increased by 15%. What is the new price?</p>",
        [("A", "$12"), ("B", "$68"), ("C", "$92"), ("D", "$95")],
        "C",
        {
            "A": "This finds only the amount of increase.",
            "B": "This subtracts the increase instead of adding it.",
            "D": "This adds 15 dollars instead of 15 percent.",
        },
        "The increase is 0.15(80) = 12, so the new price is 80 + 12 = 92.",
        ["percent-base error"],
        "percent-change",
        "Calculate a percent increase from an original value.",
    ),
    numeric(
        "ITEM-010",
        1,
        10,
        "Algebra",
        "Linear functions",
        "Use a linear equation to solve for an input.",
        "medium",
        "<p>The line y = 3x - 7 passes through the point (k, 8). What is the value of k?</p>",
        "5",
        [{"type": "exact", "value": "5"}],
        "Substitute y = 8: 8 = 3k - 7, so 15 = 3k and k = 5.",
        ["linear-function-substitution error"],
        "linear-function-input",
        "Find an input value from a linear function and output.",
    ),
    mcq(
        "ITEM-011",
        1,
        11,
        "Advanced Math",
        "Nonlinear equations in one variable",
        "Solve a factored quadratic equation.",
        "medium",
        "<p>What is the smaller solution to x^2 - 5x + 6 = 0?</p>",
        [("A", "1"), ("B", "2"), ("C", "3"), ("D", "6")],
        "B",
        {
            "A": "This chooses a factor of 6 but does not check that the two factors add to 5.",
            "C": "This is a solution, but it is the larger solution.",
            "D": "This is the product of the two solutions, not a solution.",
        },
        "Factor as (x - 2)(x - 3) = 0. The solutions are 2 and 3, so the smaller solution is 2.",
        ["factoring error", "solution-selection error"],
        "quadratic-solving",
        "Factor and interpret solutions of a quadratic equation.",
    ),
    numeric(
        "ITEM-012",
        1,
        12,
        "Geometry and Trigonometry",
        "Right triangles and trigonometry",
        "Use the Pythagorean theorem.",
        "medium",
        "<p>A right triangle has legs of lengths 9 and 12. What is the length of the hypotenuse?</p>",
        "15",
        [{"type": "exact", "value": "15"}],
        "Use a^2 + b^2 = c^2: 9^2 + 12^2 = 81 + 144 = 225, so c = 15.",
        ["pythagorean-theorem error"],
        "right-triangle-length",
        "Find a missing side length in a right triangle.",
    ),
    mcq(
        "ITEM-013",
        1,
        13,
        "Algebra",
        "Linear functions",
        "Find slope from two points.",
        "medium",
        "<p>A line passes through (2, 7) and (5, 19). What is the slope of the line?</p>",
        [("A", "3"), ("B", "4"), ("C", "6"), ("D", "12")],
        "B",
        {
            "A": "This is the change in x, not the slope.",
            "C": "This divides the change in y by 2 instead of the change in x.",
            "D": "This is the change in y, not the slope.",
        },
        "The slope is (19 - 7)/(5 - 2) = 12/3 = 4.",
        ["slope formula error"],
        "slope-from-points",
        "Calculate slope from two coordinate pairs.",
    ),
    mcq(
        "ITEM-014",
        1,
        14,
        "Advanced Math",
        "Nonlinear functions",
        "Compare symbolic function expressions.",
        "hard",
        "<p>If h(x) = 2x^2 + 3x - 5, which expression is equivalent to h(x + 1) - h(x)?</p>",
        [("A", "4x + 5"), ("B", "4x + 1"), ("C", "2x + 3"), ("D", "2x^2 + 7x")],
        "A",
        {
            "B": "This expands h(x + 1) with an incorrect constant term.",
            "C": "This treats the change in 2x^2 as 2x and includes only the +3 from the linear term.",
            "D": "This computes h(x + 1) but does not subtract h(x).",
        },
        "h(x + 1) = 2(x + 1)^2 + 3(x + 1) - 5 = 2x^2 + 7x. Subtracting h(x) gives 4x + 5.",
        ["function-composition error", "expansion error"],
        "symbolic-function-comparison",
        "Expand and compare symbolic function expressions.",
    ),
    numeric(
        "ITEM-015",
        1,
        15,
        "Problem-Solving and Data Analysis",
        "One-variable data distributions",
        "Use changes in mean to find a removed data value.",
        "hard",
        "<p>Six numbers have a mean of 18. When the largest number is removed, the mean of the remaining five numbers is 16. What is the largest number?</p>",
        "28",
        [{"type": "exact", "value": "28"}],
        "The six numbers have total 6*18 = 108. The remaining five numbers have total 5*16 = 80. The removed largest number is 108 - 80 = 28.",
        ["mean-total error", "removed-value error"],
        "mean-change-removed-value",
        "Use a change in mean to find a removed data value.",
    ),
    mcq(
        "ITEM-016",
        1,
        16,
        "Algebra",
        "Linear equations in one variable",
        "Identify a parameter that makes expressions equivalent.",
        "hard",
        "<p>For what value of a is a(2x - 3) = 10x - 15 true for all values of x?</p>",
        [("A", "3"), ("B", "5"), ("C", "10"), ("D", "15")],
        "B",
        {
            "A": "This matches the constant inside the parentheses, not the distributed expression.",
            "C": "This matches the coefficient of x before accounting for 2x.",
            "D": "This matches the constant term without considering the sign and factor.",
        },
        "Distribute to get 2ax - 3a. Matching 10x - 15 requires 2a = 10 and -3a = -15, so a = 5.",
        ["distribution error", "coefficient-matching error"],
        "equivalent-linear-expressions",
        "Match coefficients in equivalent linear expressions.",
    ),
    numeric(
        "ITEM-017",
        1,
        17,
        "Advanced Math",
        "Nonlinear equations in one variable",
        "Solve a radical equation with a domain check.",
        "hard",
        "<p>If sqrt(3x + 1) = 5, what is the value of x?</p>",
        "8",
        [{"type": "exact", "value": "8"}],
        "Square both sides to get 3x + 1 = 25. Then 3x = 24, so x = 8.",
        ["radical-equation error"],
        "radical-equation-solving",
        "Solve a simple radical equation and verify the input is valid.",
    ),
    mcq(
        "ITEM-018",
        1,
        18,
        "Advanced Math",
        "Equivalent expressions",
        "Identify excluded values for a rational expression.",
        "hard",
        "<p>For which values of x is the expression 1/(x^2 - 4x) undefined?</p>",
        [("A", "0 only"), ("B", "4 only"), ("C", "0 and 4"), ("D", "-4 and 4")],
        "C",
        {
            "A": "This finds one zero of the denominator but misses x = 4.",
            "B": "This finds one zero of the denominator but misses x = 0.",
            "D": "This factors x^2 - 4x as if it were a difference of squares.",
        },
        "The denominator factors as x(x - 4). It is zero at x = 0 and x = 4.",
        ["domain restriction error", "factoring error"],
        "rational-expression-domain",
        "Find excluded values from the denominator of a rational expression.",
    ),
    mcq(
        "ITEM-019",
        2,
        1,
        "Algebra",
        "Linear equations in one variable",
        "Solve a linear equation with variables on both sides.",
        "easy",
        "<p>If 4x - 9 = 2x + 7, what is the value of x?</p>",
        [("A", "2"), ("B", "4"), ("C", "8"), ("D", "16")],
        "C",
        {
            "A": "This divides the constant difference by the wrong coefficient.",
            "B": "This treats the right side as 7 and ignores the 2x term before solving.",
            "D": "This finds 2x but does not divide by 2.",
        },
        "Subtract 2x from both sides to get 2x - 9 = 7. Add 9 to get 2x = 16, so x = 8.",
        ["inverse-operation error"],
        "linear-equation-solving",
        "Solve an equation with variable terms on both sides.",
    ),
    mcq(
        "ITEM-020",
        2,
        2,
        "Advanced Math",
        "Equivalent expressions",
        "Apply exponent rules to a product.",
        "easy",
        "<p>Which expression is equivalent to (2x^3)(3x^2)?</p>",
        [("A", "5x^5"), ("B", "6x^5"), ("C", "6x^6"), ("D", "12x^5")],
        "B",
        {
            "A": "This adds the coefficients instead of multiplying them.",
            "C": "This multiplies the exponents instead of adding them.",
            "D": "This multiplies the coefficients by an extra factor of 2.",
        },
        "Multiply coefficients and add exponents on like bases: 2*3*x^(3+2) = 6x^5.",
        ["exponent-rule error", "coefficient operation error"],
        "exponent-rules",
        "Simplify a product of monomials.",
    ),
    mcq(
        "ITEM-021",
        2,
        3,
        "Problem-Solving and Data Analysis",
        "Probability and conditional probability",
        "Compute a basic probability from counts.",
        "easy",
        "<p>A bag contains 5 red tiles, 3 blue tiles, and 2 green tiles. If one tile is selected at random, what is the probability that it is not blue?</p>",
        [("A", "3/10"), ("B", "7/10"), ("C", "2/7"), ("D", "7/3")],
        "B",
        {
            "A": "This is the probability of blue, not not blue.",
            "C": "This compares green tiles to non-blue tiles.",
            "D": "This reverses favorable and total counts.",
        },
        "There are 10 tiles total and 7 are not blue, so the probability is 7/10.",
        ["probability complement error"],
        "basic-probability",
        "Use a complement count to find probability.",
    ),
    mcq(
        "ITEM-022",
        2,
        4,
        "Geometry and Trigonometry",
        "Lines, angles, and triangles",
        "Use triangle angle sum.",
        "easy",
        "<p>Two angles of a triangle measure 42 degrees and 68 degrees. What is the measure, in degrees, of the third angle?</p>",
        [("A", "70"), ("B", "90"), ("C", "110"), ("D", "138")],
        "A",
        {
            "B": "This assumes the triangle is right without evidence.",
            "C": "This adds the two given angles.",
            "D": "This subtracts one given angle from 180 but ignores the other.",
        },
        "The angles in a triangle sum to 180 degrees. The third angle is 180 - 42 - 68 = 70.",
        ["angle-sum error"],
        "triangle-angle-sum",
        "Find a missing angle in a triangle.",
    ),
    mcq(
        "ITEM-023",
        2,
        5,
        "Algebra",
        "Linear equations in two variables",
        "Find an intercept from a linear equation.",
        "easy",
        "<p>What is the y-intercept of the line 3x + 2y = 12?</p>",
        [("A", "2"), ("B", "3"), ("C", "4"), ("D", "6")],
        "D",
        {
            "A": "This uses the coefficient of y, not the intercept.",
            "B": "This uses the coefficient of x, not the intercept.",
            "C": "This is the x-intercept.",
        },
        "Set x = 0 to find the y-intercept: 2y = 12, so y = 6.",
        ["intercept confusion"],
        "linear-intercepts",
        "Find a y-intercept from standard form.",
    ),
    mcq(
        "ITEM-024",
        2,
        6,
        "Advanced Math",
        "Nonlinear functions",
        "Identify the vertex of a quadratic in vertex form.",
        "easy",
        "<p>The function q(x) = (x - 4)^2 + 7 is graphed in the xy-plane. What is the vertex of the graph?</p>",
        [("A", "(-4, 7)"), ("B", "(4, 7)"), ("C", "(7, 4)"), ("D", "(4, -7)")],
        "B",
        {
            "A": "This uses the sign inside the parentheses without reversing it.",
            "C": "This switches the x- and y-coordinates.",
            "D": "This changes the sign of the vertical shift.",
        },
        "A quadratic in vertex form (x - h)^2 + k has vertex (h, k), so the vertex is (4, 7).",
        ["vertex-form error"],
        "quadratic-vertex-form",
        "Identify a vertex from quadratic vertex form.",
    ),
    mcq(
        "ITEM-025",
        2,
        7,
        "Algebra",
        "Linear functions",
        "Identify the slope of a parallel line.",
        "medium",
        "<p>A line is parallel to y = -3x + 2. What is the slope of the line?</p>",
        [("A", "-3"), ("B", "-1/3"), ("C", "1/3"), ("D", "2")],
        "A",
        {
            "B": "This uses the negative reciprocal, which applies to perpendicular lines.",
            "C": "This uses the reciprocal and changes the sign.",
            "D": "This identifies the y-intercept of the given line.",
        },
        "Parallel lines have the same slope. The slope of y = -3x + 2 is -3.",
        ["parallel-slope error"],
        "linear-slope-relationships",
        "Identify slopes of parallel lines.",
    ),
    numeric(
        "ITEM-026",
        2,
        8,
        "Advanced Math",
        "Nonlinear equations in one variable",
        "Solve an exponential equation with a common base.",
        "medium",
        "<p>If 2^(x + 1) = 32, what is the value of x?</p>",
        "4",
        [{"type": "exact", "value": "4"}],
        "Since 32 = 2^5, x + 1 = 5 and x = 4.",
        ["exponent-equation error"],
        "exponential-equation-solving",
        "Solve an exponential equation by matching powers of the same base.",
    ),
    mcq(
        "ITEM-027",
        2,
        9,
        "Geometry and Trigonometry",
        "Lines, angles, and triangles",
        "Use area scaling for similar figures.",
        "medium",
        "<p>Two similar triangles have corresponding side lengths in the ratio 3:5. If the area of the smaller triangle is 36 square units, what is the area of the larger triangle?</p>",
        [("A", "60"), ("B", "144"), ("C", "100"), ("D", "180")],
        "C",
        {
            "A": "This scales area by the side-length ratio instead of the square of the ratio.",
            "B": "This treats the side scale factor as 2 instead of 5/3, then squares that incorrect factor.",
            "D": "This multiplies by 5 instead of using the squared scale factor.",
        },
        "Area scales by the square of the side scale factor. The larger area is 36*(5/3)^2 = 36*(25/9) = 100.",
        ["scale-factor error"],
        "similar-figure-area",
        "Use squared scale factors for areas of similar figures.",
    ),
    numeric(
        "ITEM-028",
        2,
        10,
        "Algebra",
        "Linear equations in one variable",
        "Solve a decimal-coefficient linear equation.",
        "medium",
        "<p>If 0.25x + 6 = 18, what is the value of x?</p>",
        "48",
        [{"type": "exact", "value": "48"}],
        "Subtract 6 to get 0.25x = 12. Since 0.25 = 1/4, x = 48.",
        ["decimal-coefficient error"],
        "linear-equation-decimals",
        "Solve a linear equation with decimal coefficients.",
    ),
    mcq(
        "ITEM-029",
        2,
        11,
        "Advanced Math",
        "Equivalent expressions",
        "Factor a quadratic expression.",
        "medium",
        "<p>Which expression is equivalent to x^2 + 7x + 10?</p>",
        [("A", "(x + 5)(x + 2)"), ("B", "(x - 5)(x - 2)"), ("C", "(x + 10)(x + 1)"), ("D", "(x + 7)(x + 10)")],
        "A",
        {
            "B": "This gives the correct factors with incorrect signs.",
            "C": "This has the right product but the middle term would be 11x.",
            "D": "This uses the coefficient and constant as factors directly.",
        },
        "Find two numbers that multiply to 10 and add to 7: 5 and 2. The factorization is (x + 5)(x + 2).",
        ["factoring error"],
        "quadratic-factoring",
        "Factor a monic quadratic expression.",
    ),
    numeric(
        "ITEM-030",
        2,
        12,
        "Problem-Solving and Data Analysis",
        "Percentages",
        "Find the whole from a percent and part.",
        "medium",
        "<p>Thirty percent of n is 45. What is the value of n?</p>",
        "150",
        [{"type": "exact", "value": "150"}],
        "Set 0.30n = 45. Dividing by 0.30 gives n = 150.",
        ["percent-base error"],
        "percent-whole-from-part",
        "Find an original quantity from a percent amount.",
    ),
    mcq(
        "ITEM-031",
        2,
        13,
        "Algebra",
        "Linear functions",
        "Interpret a coefficient in a linear model.",
        "medium",
        "<p>A service charge is modeled by C = 25 + 8h, where C is the total cost in dollars for h hours. What does 8 represent in this model?</p>",
        [("A", "The fixed cost before any hours are added"), ("B", "The number of hours purchased"), ("C", "The cost per hour"), ("D", "The total cost for 8 hours")],
        "C",
        {
            "A": "The fixed cost is the constant 25.",
            "B": "The variable h represents the number of hours.",
            "D": "The coefficient 8 is a rate, not a total for 8 hours.",
        },
        "In C = 25 + 8h, the coefficient of h is the rate of change, so the cost is 8 dollars per hour.",
        ["linear-model interpretation error"],
        "linear-model-rate",
        "Interpret slope or rate in a linear model.",
    ),
    mcq(
        "ITEM-032",
        2,
        14,
        "Advanced Math",
        "Nonlinear equations in one variable",
        "Solve an absolute value equation.",
        "hard",
        "<p>What are the solutions to |x - 2| = 5?</p>",
        [("A", "-3 and 7"), ("B", "3 and 7"), ("C", "-7 and 3"), ("D", "7 only")],
        "A",
        {
            "B": "This solves x - 2 = 5 but handles the negative case incorrectly.",
            "C": "This changes the sign of the wrong term.",
            "D": "This includes only the positive-distance solution.",
        },
        "The equation means x - 2 = 5 or x - 2 = -5, so x = 7 or x = -3.",
        ["absolute-value branch error"],
        "absolute-value-equations",
        "Solve an absolute value equation with two solutions.",
    ),
    numeric(
        "ITEM-033",
        2,
        15,
        "Geometry and Trigonometry",
        "Right triangles and trigonometry",
        "Use a trigonometric ratio and a Pythagorean relationship.",
        "hard",
        "<p>In a right triangle, sin(theta) = 3/5 and the hypotenuse has length 20. What is the length of the leg adjacent to theta?</p>",
        "16",
        [{"type": "exact", "value": "16"}],
        "If sin(theta) = 3/5, the opposite leg and hypotenuse are in the ratio 3:5. With hypotenuse 20, the scale factor is 4, so the opposite leg is 12. The adjacent leg is sqrt(20^2 - 12^2) = sqrt(256) = 16.",
        ["trig-ratio error", "pythagorean-theorem error"],
        "right-triangle-trigonometry",
        "Use a trigonometric ratio to find a side length in a right triangle.",
    ),
    mcq(
        "ITEM-034",
        2,
        16,
        "Algebra",
        "Linear inequalities in one or two variables",
        "Solve a multi-step linear inequality.",
        "hard",
        "<p>Which inequality is equivalent to 2(x - 3) &lt;= 10?</p>",
        [("A", "x &lt;= 2"), ("B", "x &lt;= 8"), ("C", "x &gt;= 8"), ("D", "x &lt;= 13")],
        "B",
        {
            "A": "This subtracts 6 from 10 after distributing instead of adding 6.",
            "C": "This reverses the inequality even though division is by a positive number.",
            "D": "This ignores the factor of 2 and solves x - 3 <= 10 before adding 3.",
        },
        "Distribute or divide by 2: x - 3 <= 5, so x <= 8.",
        ["inequality solving error"],
        "linear-inequality-solving",
        "Solve a two-step linear inequality.",
    ),
    numeric(
        "ITEM-035",
        2,
        17,
        "Advanced Math",
        "Nonlinear functions",
        "Evaluate a composition of functions.",
        "hard",
        "<p>If f(x) = x^2 + 2 and g(x) = 3x - 1, what is f(g(2))?</p>",
        "27",
        [{"type": "exact", "value": "27"}],
        "First find g(2) = 3(2) - 1 = 5. Then f(5) = 5^2 + 2 = 27.",
        ["function-composition error"],
        "function-composition",
        "Evaluate a composition of two functions.",
    ),
    mcq(
        "ITEM-036",
        2,
        18,
        "Advanced Math",
        "Nonlinear equations in one variable",
        "Solve a rational equation.",
        "hard",
        "<p>If (x + 2)/(x - 1) = 3 and x is not equal to 1, what is the value of x?</p>",
        [("A", "2/5"), ("B", "5/2"), ("C", "-5/2"), ("D", "5")],
        "B",
        {
            "A": "This reverses the final division step and divides 2 by 5 instead of 5 by 2.",
            "C": "This changes the sign when moving terms after clearing the denominator.",
            "D": "This finds the numerator difference but does not divide by 2.",
        },
        "Multiply by x - 1: x + 2 = 3x - 3. Then 5 = 2x, so x = 5/2.",
        ["rational-equation error"],
        "rational-equation-solving",
        "Solve a rational equation with a domain restriction.",
    ),
]


def main() -> None:
    OUTPUT_PATH.write_text(json.dumps({"items": ITEMS}, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(ITEMS)} items to {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
